name: Build and Push Images

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

env:
  AWS_REGION: us-east-1
  ECR_REGISTRY: 552823821096.dkr.ecr.us-east-1.amazonaws.com

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify application files
        run: |
          echo "======================================"
          echo "Git commit:"
          git rev-parse HEAD
          echo "======================================"

          echo "Worker Dockerfile:"
          echo "======================================"
          cat application/worker/Dockerfile
          echo "======================================"

          echo "Worker directory:"
          echo "======================================"
          ls -la application/worker
          echo "======================================"

      - name: Show GitHub repository IDs
        run: |
           echo "Repository: ${{ github.repository }}"
           echo "Owner ID: ${{ github.repository_owner_id }}"
           echo "Repository ID: ${{ github.repository_id }}"
           echo "Ref: ${{ github.ref }}"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::552823821096:role/voting-github-actions-role
          aws-region: us-east-1
          role-session-name: GitHubActions

      - name: Check AWS identity
        run: |
          aws sts get-caller-identity

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build voting app
        run: |
          docker build \
            -t $ECR_REGISTRY/voting-app:latest \
            ./application/vote

      - name: Build result app
        run: |
          docker build \
            -t $ECR_REGISTRY/result-app:latest \
            ./application/result

      - name: Build worker
        run: |
          echo "======================================"
          echo "Building worker"
          echo "======================================"

          echo "Dockerfile being used:"
          cat ./application/worker/Dockerfile

          echo "======================================"

          docker build \
            --no-cache \
            -t $ECR_REGISTRY/worker:latest \
            ./application/worker

      - name: Push voting app
        run: |
          docker push $ECR_REGISTRY/voting-app:latest

      - name: Push result app
        run: |
          docker push $ECR_REGISTRY/result-app:latest

      - name: Push worker
        run: |
          docker push $ECR_REGISTRY/worker:latest

      - name: Deploy to ECS
        run: |
          echo "Updating ECS services..."

          aws ecs update-service \
            --cluster voting-app-cluster \
            --service voting-service \
            --force-new-deployment

          aws ecs update-service \
            --cluster voting-app-cluster \
            --service worker-service \
            --force-new-deployment

          aws ecs update-service \
            --cluster voting-app-cluster \
            --service result-service \
            --force-new-deployment

          echo "ECS deployment started."